In [1]:
import numpy as np
import torch

### **1. List vs Array vs Tensor**

In [2]:
data = [[1,2],[3,4]]
data

[[1, 2], [3, 4]]

In [3]:
type(data)

list

In [4]:
data = np.array(data)
data

array([[1, 2],
       [3, 4]])

In [5]:
type(data)

numpy.ndarray

#### **1.1 Converting Numpy Array to Tensors**

In [6]:
data = torch.tensor(data)
data

tensor([[1, 2],
        [3, 4]])

In [7]:
type(data)

torch.Tensor

### **2. How to initialize tensors**

In [8]:
# Creating an empty tensor
x = torch.empty(5,3)
x

tensor([[9.6920e+23, 3.0732e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

In [9]:
type(x)

torch.Tensor

In [10]:
# Creating a randomly initialized tensor
x = torch.rand(5,3)
x

tensor([[0.8081, 0.8971, 0.4865],
        [0.0604, 0.1776, 0.3862],
        [0.8486, 0.9998, 0.5671],
        [0.8547, 0.9353, 0.1808],
        [0.9411, 0.5058, 0.4958]])

In [11]:
# Constructing tensor from data directly 
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

### **3. Tensor Operations**

In [12]:
# Adding two tensors
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x+y)

tensor([[0.9094, 1.3584, 0.8794],
        [0.9421, 0.8131, 0.5405],
        [1.0408, 1.3321, 1.5062],
        [0.6661, 0.4638, 1.5444],
        [1.4272, 0.4630, 0.5839]])


In [13]:
x = torch.randn(4,4)
x

tensor([[-2.4884,  2.3911,  0.2228,  0.4022],
        [ 0.3997,  0.7231,  0.5471, -0.5833],
        [-0.2201, -0.6346, -0.1088, -0.3521],
        [ 0.9786, -0.1676, -1.7527, -0.5348]])

In [46]:
# Reshaping tensors
x = torch.rand(3,4)
x

tensor([[0.2528, 0.1757, 0.4884, 0.0454],
        [0.7803, 0.5354, 0.8405, 0.3409],
        [0.7336, 0.5902, 0.8958, 0.4280]])

In [48]:
y = x.view(12)
y

tensor([0.2528, 0.1757, 0.4884, 0.0454, 0.7803, 0.5354, 0.8405, 0.3409, 0.7336,
        0.5902, 0.8958, 0.4280])

In [50]:
z = x.view(2, 6)
z

tensor([[0.2528, 0.1757, 0.4884, 0.0454, 0.7803, 0.5354],
        [0.8405, 0.3409, 0.7336, 0.5902, 0.8958, 0.4280]])

### **4. Tensor Attributes**

In [15]:
# Checking Data Type
data.dtype

torch.int64

In [16]:
np_array = np.random.rand(4,3)
torch.tensor(np_array)

tensor([[0.6597, 0.0273, 0.6696],
        [0.0867, 0.2811, 0.6354],
        [0.6068, 0.3029, 0.2677],
        [0.8439, 0.0734, 0.6318]], dtype=torch.float64)

In [17]:
torch.from_numpy(np_array)

tensor([[0.6597, 0.0273, 0.6696],
        [0.0867, 0.2811, 0.6354],
        [0.6068, 0.3029, 0.2677],
        [0.8439, 0.0734, 0.6318]], dtype=torch.float64)

In [18]:
# Tensor with all ones
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
# Tensor with all zeroes
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
my_tensor = torch.rand(3,4)
my_tensor

tensor([[0.5396, 0.1249, 0.5502, 0.7076],
        [0.8670, 0.9282, 0.1736, 0.4721],
        [0.7755, 0.4231, 0.2287, 0.4352]])

In [21]:
my_tensor.dtype

torch.float32

In [22]:
# check current device of tensor
my_tensor.device

device(type='cpu')

In [23]:
# bash command to check GPU details
! nvidia-smi

Wed Jun 16 14:53:41 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [25]:
# changing location of tensor from CPU to GPU
my_tensor = my_tensor.to("cuda")

In [26]:
# Indexing
my_tensor[:,1:3]

tensor([[0.1249, 0.5502],
        [0.9282, 0.1736],
        [0.4231, 0.2287]], device='cuda:0')

In [27]:
# Element-wise multiplication 
my_tensor.mul(my_tensor)

tensor([[0.2912, 0.0156, 0.3028, 0.5007],
        [0.7517, 0.8615, 0.0301, 0.2229],
        [0.6013, 0.1790, 0.0523, 0.1894]], device='cuda:0')

In [30]:
# Matrix multiplication
my_tensor.matmul(my_tensor.T)

tensor([[1.1102, 1.0134, 0.9051],
        [1.0134, 1.8662, 1.3101],
        [0.9051, 1.3101, 1.0220]], device='cuda:0')

In [31]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[1.1102, 1.0134, 0.9051],
        [1.0134, 1.8662, 1.3101],
        [0.9051, 1.3101, 1.0220]], device='cuda:0')

In [32]:
my_tensor @ my_tensor.T

tensor([[1.1102, 1.0134, 0.9051],
        [1.0134, 1.8662, 1.3101],
        [0.9051, 1.3101, 1.0220]], device='cuda:0')

In [33]:
# sum row-wise
my_tensor.sum(axis=0)

tensor([2.1821, 1.4762, 0.9525, 1.6149], device='cuda:0')

In [34]:
# sum column-wise
my_tensor.sum(axis=1)

tensor([1.9224, 2.4408, 1.8624], device='cuda:0')

In [35]:
#torch.max, torch.min

In [36]:
# Concatenate two tensors
torch.cat([my_tensor, my_tensor], dim=1)

tensor([[0.5396, 0.1249, 0.5502, 0.7076, 0.5396, 0.1249, 0.5502, 0.7076],
        [0.8670, 0.9282, 0.1736, 0.4721, 0.8670, 0.9282, 0.1736, 0.4721],
        [0.7755, 0.4231, 0.2287, 0.4352, 0.7755, 0.4231, 0.2287, 0.4352]],
       device='cuda:0')

In [37]:
# Apply softmax function to this tensor
torch.nn.functional.softmax(my_tensor, dim=0)

tensor([[0.2737, 0.2183, 0.4147, 0.3919],
        [0.3797, 0.4875, 0.2846, 0.3097],
        [0.3465, 0.2942, 0.3007, 0.2984]], device='cuda:0')

In [38]:
# Check shape of tensor
my_tensor.shape

torch.Size([3, 4])

In [39]:
my_tensor.size()

torch.Size([3, 4])

In [40]:
# In case of images - batch_size,no. of channels., height and width 
torch.rand(10,3,128,128)

tensor([[[[4.6857e-01, 1.8513e-01, 5.0626e-01,  ..., 3.0306e-01,
           7.7199e-01, 2.6273e-01],
          [5.8362e-01, 9.9790e-01, 5.1723e-02,  ..., 2.6674e-01,
           6.3302e-01, 8.9822e-01],
          [6.2277e-01, 3.4341e-01, 3.7952e-01,  ..., 1.4786e-01,
           1.2929e-01, 3.9379e-01],
          ...,
          [4.2419e-01, 8.7479e-01, 7.8317e-01,  ..., 4.3435e-01,
           2.2437e-02, 6.6827e-01],
          [4.9245e-01, 8.3815e-01, 9.9656e-02,  ..., 8.8297e-01,
           3.7486e-01, 3.6218e-01],
          [2.1002e-01, 1.2146e-01, 4.0676e-01,  ..., 1.1137e-01,
           7.9917e-01, 1.8700e-01]],

         [[9.6915e-01, 5.0923e-01, 7.1679e-01,  ..., 9.4559e-01,
           4.0547e-02, 5.3626e-01],
          [1.9779e-01, 8.0904e-02, 7.4385e-01,  ..., 8.1185e-02,
           9.0534e-01, 1.2542e-01],
          [9.1139e-01, 8.2960e-01, 8.4164e-01,  ..., 9.6508e-02,
           5.7058e-01, 2.3066e-01],
          ...,
          [4.2503e-01, 1.2604e-01, 6.0517e-01,  ..., 3.4033

In [45]:
# Clip function - clip all values below min to min and above max to max
# tensor.clip(min, max)
my_tensor.clip(0.2, 0.8)

tensor([[0.5396, 0.2000, 0.5502, 0.7076],
        [0.8000, 0.8000, 0.2000, 0.4721],
        [0.7755, 0.4231, 0.2287, 0.4352]], device='cuda:0')

In [42]:
# Convert tensor to numpy array
my_tensor.cpu().detach().numpy()

array([[0.5396128 , 0.12494659, 0.55022776, 0.707585  ],
       [0.8669936 , 0.9281953 , 0.17356008, 0.4720968 ],
       [0.7754562 , 0.42307013, 0.22868574, 0.43518507]], dtype=float32)