### **Autograd**

- It is an automatic differentitaion engine in Pytorch

In [1]:
import torch

In [2]:
# requires_grad - Is True if gradients need to be computed for this Tensor
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [3]:
a

tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
y = a**3 - b**2

In [6]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [7]:
# dy/da = 3*a**2 = 75
# dy/db = 2**b = -12

#### **Gradients can't be calculated until we perform backward pass**

In [8]:
# calculate gradient using tensor_name.grad()
print(a.grad)

None


In [9]:
print(b.grad)

None


#### **Performing backward pass and calculating gradient**

In [10]:
# Backward Pass
y.backward()

In [11]:
print(a.grad)
print(b.grad)

tensor([75.])
tensor([-12.])


#### **Let's try on a simple equation -**
y=w*x+b 

In [12]:
w = torch.randn(10, 1, requires_grad=True)
w

tensor([[ 1.2565],
        [-1.1536],
        [ 0.4455],
        [ 0.0591],
        [-0.0674],
        [ 1.1324],
        [-1.3814],
        [ 0.6829],
        [ 0.1139],
        [-0.9607]], requires_grad=True)

In [13]:
x = torch.randn(1, 10, requires_grad=True)
x

tensor([[-0.9297,  2.8417, -1.0044,  0.3722, -0.4546,  0.1745,  0.5309, -1.0483,
          0.5504, -0.4810]], requires_grad=True)

In [14]:
output = torch.matmul(x, w)+b
output

tensor([[0.4321]], grad_fn=<AddBackward0>)

In [15]:
loss = 1 - output
loss

tensor([[0.5679]], grad_fn=<RsubBackward1>)

In [16]:
loss.backward()

In [17]:
w.grad

tensor([[ 0.9297],
        [-2.8417],
        [ 1.0044],
        [-0.3722],
        [ 0.4546],
        [-0.1745],
        [-0.5309],
        [ 1.0483],
        [-0.5504],
        [ 0.4810]])

In [18]:
# torch.no_grad() basically skips the gradient calculation over the weights
# reduces memory consumption
# the result of every computation will have requires_grad=False, even when the inputs have requires_grad=True.
with torch.no_grad():
  w = w - 0.001 * w.grad.data

In [19]:
w

tensor([[ 1.2556],
        [-1.1507],
        [ 0.4444],
        [ 0.0595],
        [-0.0679],
        [ 1.1326],
        [-1.3809],
        [ 0.6818],
        [ 0.1145],
        [-0.9612]])

#### **no_grad function**

- To stop PyTorch from tracking the history and forming the backward graph, the code can be wrapped inside with torch.no_grad() 
- It will make the code run faster whenever gradient tracking is not needed.